on:
  watch:
    types: started
  # push:
  #    Sequence of patterns matched against refs/tags
    # tags:
    # - '*' # Tag events

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: checkout codes
        uses: actions/checkout@v1
      - name: build
        id: build_ipk
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo ::set-output name=tag_name::${TAG}
          mkdir -p /tmp/luci-app-nut/usr/lib/lua/luci /tmp/luci-app-nut/www/
          [ -d $GITHUB_WORKSPACE/luci-app-nut/luasrc ] && cp -R $GITHUB_WORKSPACE/luci-app-nut/luasrc/* /tmp/luci-app-nut/usr/lib/lua/luci/
          [ -d $GITHUB_WORKSPACE/luci-app-nut/root ] && cp -R $GITHUB_WORKSPACE/luci-app-nut/root/* /tmp/luci-app-nut/
          [ -d $GITHUB_WORKSPACE/luci-app-nut/po ] && sudo -E apt-get -y install gcc make && \
          mkdir -p /tmp/po2lmo && mkdir -p /tmp/luci-app-nut/usr/lib/lua/luci/i18n/ && \
          wget -O /tmp/po2lmo/po2lmo.c https://raw.githubusercontent.com/openwrt/luci/openwrt-18.06/modules/luci-base/src/po2lmo.c && \
          wget -O /tmp/po2lmo/Makefile https://raw.githubusercontent.com/openwrt/luci/openwrt-18.06/modules/luci-base/src/Makefile && \
          wget -O /tmp/po2lmo/template_lmo.h https://raw.githubusercontent.com/openwrt/luci/openwrt-18.06/modules/luci-base/src/template_lmo.h && \
          wget -O /tmp/po2lmo/template_lmo.c https://raw.githubusercontent.com/openwrt/luci/openwrt-18.06/modules/luci-base/src/template_lmo.c && \
          cd /tmp/po2lmo && make po2lmo && ./po2lmo $GITHUB_WORKSPACE/luci-app-nut/po/zh-cn/nut.po /tmp/luci-app-nut/usr/lib/lua/luci/i18n/nut.zh-cn.lmo
          mkdir -p /tmp/luci-app-nut/CONTROL
          cat >/tmp/luci-app-nut/CONTROL/control <<EOF
          Package: luci-app-nut
          Version: ${TAG}
          Depends: libc
          Source: package/doushang/luci-app-nut
          SourceName: luci-app-nut
          License: AGPL-3.0
          Section: luci
          Maintainer: <https://github.com/doushang/luci-app-nut>
          Architecture: all
          Description:  LuCI Support for nut
          EOF
          cat >/tmp/luci-app-nut/CONTROL/postinst <<"EOF"
          #!/bin/sh
          [ "${IPKG_NO_SCRIPT}" = "1" ] && exit 0
          [ -x ${IPKG_INSTROOT}/lib/functions.sh ] || exit 0
          . ${IPKG_INSTROOT}/lib/functions.sh
          default_postinst $0 $@
          EOF
          chmod +x /tmp/luci-app-nut/CONTROL/postinst
          cat >/tmp/luci-app-nut/CONTROL/prerm <<"EOF"
          #!/bin/sh
          [ -x ${IPKG_INSTROOT}/lib/functions.sh ] || exit 0
          . ${IPKG_INSTROOT}/lib/functions.sh
          default_prerm $0 $@
          EOF
          chmod +x /tmp/luci-app-nut/CONTROL/prerm
          wget -O /tmp/ipkg-build https://raw.githubusercontent.com/openwrt/openwrt/openwrt-18.06/scripts/ipkg-build && \
          chmod +x /tmp/ipkg-build && \
          /tmp/ipkg-build -o root -g root /tmp/luci-app-nut /tmp
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: /tmp/luci-app-nut_${{ steps.build_ipk.outputs.tag_name }}_all.ipk
          asset_name: luci-app-nut_${{ steps.build_ipk.outputs.tag_name }}_all.ipk
          asset_content_type: application/octet-stream
