name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build the IPK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Docker Build
      run: |
        mkdir bin
        cp -rf ./luci-app-nut ./bin/
        docker pull openwrtorg/sdk:x86-64-21.02-SNAPSHOT
        docker run --rm -u root -v "$(pwd)"/bin/:/home/build/openwrt/bin -v ${{ github.workspace }}/.github/workflows:/home/build/workflows openwrtorg/sdk:x86-64-21.02-SNAPSHOT /bin/sh /home/build/workflows/build.sh
    - name: Upload app
      uses: actions/upload-artifact@v3.1.0
      with:
        name: pack
        path: ./bin/packages/x86_64/base/*nut*.ipk
        if-no-files-found: error
    - name: Upload Log
      if: ${{ always() }}
      uses: actions/upload-artifact@v3.1.0
      with:
        name: buildlog
        path: bin/logs.tar.xz
